# Generated by Django 5.1 on 2025-04-11 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="vendor",
        ),
    ]
