# Generated by Django 5.1 on 2025-07-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_item_options_alter_item_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="has_varieties",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField(default=0)),
                (
                    "base_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="store.item",
                    ),
                ),
            ],
        ),
    ]
