# Generated by Django 5.1 on 2025-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_item_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
