# Generated by Django 5.1 on 2025-04-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_item_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="store.store",
            ),
        ),
    ]
