# Generated by Django 5.1 on 2025-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_item_has_varieties_alter_item_price_variety"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeinventory",
            name="price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
