# Generated by Django 5.1 on 2025-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_storeinventory_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeinventory",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
