# Generated by Django 5.1 on 2025-04-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_delivery_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeinventory",
            name="min_stock_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
