# Generated by Django 5.1 on 2025-04-17 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_stockalert"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockAlert",
        ),
    ]
