# Generated by Django 5.1 on 2025-04-23 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_stockalert"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Delivery",
        ),
    ]
