# Generated by Django 5.1 on 2025-04-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalusage",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
