# Generated by Django 5.1 on 2025-04-16 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0002_internalusage_usagedetail_delete_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagedetail",
            name="price_per_item",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usagedetail",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
