# Generated by Django 5.1 on 2025-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0003_usagedetail_price_per_item_usagedetail_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagedetail",
            name="price_per_item",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
