# Generated by Django 5.1 on 2025-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0004_alter_usagedetail_price_per_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagedetail",
            name="price_per_item",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
