# Generated by Django 5.1 on 2025-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0005_alter_usagedetail_price_per_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalusage",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
