# Generated by Django 5.1 on 2025-04-23 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0006_internalusage_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internalusage",
            name="slug",
        ),
    ]
