# Generated by Django 5.1 on 2025-04-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
