# Generated by Django 5.1 on 2025-04-11 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="customer",
        ),
    ]
