# Generated by Django 5.1 on 2025-04-14 14:20

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_date_joined_alter_profile_last_login"),
        ("store", "0004_delivery_store"),
        ("transactions", "0002_remove_sale_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="vendor", unique=True
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Date"
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Successful")],
                        default="P",
                        max_length=1,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="store.store",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="accounts.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Price per item (Ksh)",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.item"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="transactions.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
