# Generated by Django 5.1 on 2025-04-28 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transfer_transferdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="amount_transferred",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="tax_percentage",
        ),
    ]
