# Generated by Django 5.1 on 2025-04-15 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_purchaseorder_purchasedetail_delete_purchase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["-date_added"],
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.RemoveField(
            model_name="purchasedetail",
            name="price",
        ),
    ]
