# Generated by Django 5.1 on 2025-05-02 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_purchaseorder_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="created_by",
        ),
    ]
