# Generated by Django 5.1 on 2025-07-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_item_has_varieties_alter_item_price_variety"),
        ("transactions", "0006_purchaseorder_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="variety",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.variety",
            ),
        ),
    ]
