# Generated by Django 5.1 on 2025-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_alter_sale_receipt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="receipt_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
