# Generated by Django 5.1 on 2025-04-16 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_sale_receipt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="receipt_number",
            field=models.CharField(
                default=django.utils.timezone.now,
                editable=False,
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
